---
- name: Softlink creation playbook
  hosts: all
  become: yes
  tasks:
    - name: create empty file /opt/itadmin/blog.txt
      file: 
        path: /opt/itadmin/blog.txt
        state: touch
        owner: tony
        group: tony
      when: "inventory_hostname in 'stapp01'"

    - name: create empty file /opt/itadmin/story.txt
      file: 
        path: /opt/itadmin/story.txt
        state: touch
        owner: steve
        group: steve
      when: "inventory_hostname in 'stapp02'"

    - name: create empty file /opt/itadmin/media.txt
      file: 
        path: /opt/itadmin/media.txt
        state: touch
        owner: banner
        group: banner
      when: "inventory_hostname in 'stapp03'"
    - name: create Softlink /opt/itadmin/ to app server
      file: 
        src: /opt/itadmin
        dest: /var/www/html
        state: link
      when: "inventory_hostname in 'stapp01' or inventory_hostname in 'stapp02' or inventory_hostname in 'stapp03'"

