apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
  labels:
    app: pod-nautilus
spec:
  volumes: 
    - name: pvc-nautilus
      persistentVolumeClaim:
        claimName: pvc-nautilus
  containers:
  - name: container-nautilus
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: pvc-nautilus
      mountPath: /usr/local/apache2/htdocs/
  

