apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    db: master-db
    tier: backend
    
spec:
  replicas: 1
  selector:
    matchLabels:
      db: master-db
      tier: backend
  template:
    metadata:
      labels:
        db: master-db
        tier: backend
    spec:
      containers:
      - name: master-redis-datacenter
        image: redis
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 6379
