apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    db: slave-db
    tier: backend 
spec:
  replicas: 2
  selector:
    matchLabels:
      db: slave-db
      tier: backend
  template:
    metadata:
      labels:
        db: slave-db
        tier: backend
    spec:
      containers:
      - name: slave-redis-datacenter
        image: gcr.io/google_samples/gb-redisslave:v3
        env:
          - name: GET_HOSTS_FROM
            value: dns
        resources:
          requests:
            memory: 100Mi 
            cpu: 100m
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 6379
