apiVersion: v1
kind: Service
metadata:
  name: iron-gallery-service-xfusion
  namespace: iron-namespace-xfusion
spec:
  selector:
    run: iron-gallery 
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32678
  type: NodePort
  
