ENV RAILS_ENV="production" \
    BUNDLE_DEPLOYMENT="1" \
    BUNDLE_PATH="/usr/local/bundle" \
    BUNDLE_WITHOUT="development" \
    DEV_DATABASE_NAME="myapp_development" \
    TEST_DATABASE_NAME="myapp_test" \
    PROD_DATABASE="myapp_production" \
    DB_HOST="pgsql-app" \
    DB_PORT="5432" \
    DB_USERNAME="postgres" \
    DB_PASSWORD="Admin@123\$%"