# Create a job countdown-nautilus.

# The spec template should be named as countdown-nautilus (under metadata), and the container should be named as container-countdown-nautilus

# Use image ubuntu with latest tag only and remember to mention tag i.e ubuntu:latest, and restart policy should be Never.

# Use command sleep 5

apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-nautilus
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: container-countdown-nautilus
        image: ubuntu:latest
        command: [ "sleep", "5" ]
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-nautilus
spec:
  template:
    metadata:
      name: countdown-nautilus
    spec:
      containers:
      - name: container-countdown-nautilus
        image: fedora:latest
        command: ["sleep", "5"]
      restartPolicy: Never
