---
- name: Lineinfile Playbook
  hosts: all
  become: true
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
      
    - name: httpd service start 
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Create index.html file in /var/www/html
      file:
        path: /var/www/html/index.html
        state: touch
        owner: apache
        group: apache
        mode: 0744

    - name: Add content in file
      copy:
        path: /var/www/html/index.html
        content: |
          This is a Nautilus sample file, created using Ansible!
            
    - name: add some line at the top of file in /var/www/html/index.html
      lineinfile: 
        path: /var/www/html/index.html
        line: 'Welcome to xFusionCorp Industries!'
        insertbefore: '^This is a Nautilus sample file, created using Ansible!'
      
    # - name: replace
    #   replace:
    #     path: /var/www/html/index.html
    #     regexp: '.*'
    #     replace: 'Welcome to xFusionCorp Industries!'
    #   notify: restart httpd
  
    
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

