apiVersion: v1
kind: Pod
metadata:
  name: nginx-phpfpm
  labels:
    name: nginx-pod
spec:
  volumes: 
    - name: nginx-config-volume
      configMap:
        name: nginx-config
    - name: shared-files
      emptyDir: {}
      
  containers:
  - name: nginx-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: shared-files
        mountPath: /var/www/html
      - name: nginx-config-volume
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
  - name: php-fpm-container
    image: php:8.2-fpm-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: shared-files
        mountPath: /var/www/html
    ports:
      - containerPort: 8099
