# Create a namespace named as httpd-namespace-datacenter.

# Create a deployment named as httpd-deployment-datacenter
#  under newly created namespace. For the deployment use httpd image with latest tag only 
# and remember to mention the tag i.e httpd:latest, and make sure replica counts are 2.

# Create a service named as httpd-service-datacenter under same namespace to expose the deployment, 
# nodePort should be 30004.

# Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.


---
apiVersion: v1
kind: Namespace
metadata:
  name: httpd-namespace-datacenter


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-datacenter
  labels:
    app: httpd
  namespace: httpd-namespace-datacenter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service-datacenter
  namespace: httpd-namespace-datacenter
spec:
  selector:
    app: httpd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  type: NodePort


# ~$: kubectl get all -n httpd-namespace-datacenter

#     NAME                                               READY   STATUS    RESTARTS   AGE
#     pod/httpd-deployment-datacenter-67c544845c-45d7l   1/1     Running   0          30s
#     pod/httpd-deployment-datacenter-67c544845c-mw29g   1/1     Running   0          30s

#     NAME                               TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
#     service/httpd-service-datacenter   NodePort   10.96.163.209   <none>        80:30004/TCP   89s

#     NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
#     deployment.apps/httpd-deployment-datacenter   2/2     2            2           30s

#     NAME                                                     DESIRED   CURRENT   READY   AGE
#     replicaset.apps/httpd-deployment-datacenter-67c544845c   2         2         2       30s