apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass
type: Opaque
data:
  password: UjAwdA==

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
type: Opaque
data:
  username: a29kZWtsb3VkX2FpbQ==
  password: QnJ1Q1N0bk1UNQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url
type: Opaque
data:
  database: a29kZWtsb3VkX2RiNQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-host
type: Opaque
data:
  host: ZHJ1cGFsLW15c3FsLXNlcnZpY2U=
