apiVersion: v1
kind: Service
metadata:
  name: python-service-devops
spec:
  selector:
    app: python_app
  ports:
  - port: 8080
    targetPort: 8080  
    nodePort: 32345
  type: NodePort
