# 1.) Create a deployment named grafana-deployment-xfusion using any grafana image for Grafana app.
#     Set other parameters as per your choice.


# 2.) Create NodePort type service with nodePort 32000 to expose the app.


# You need not to make any configuration changes inside the Grafana app once deployed,
#     just make sure you are able to access the Grafana login page.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment-xfusion
  labels:
    app: grafana
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes: 
        - name: grafana-vol
          emptyDir: {} 
      containers:
      - name: grafana-container
        image: grafana/grafana
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        volumeMounts:
          - name: grafana-vol
            mountPath: /var/lib/grafana
        ports:
        - containerPort: 3000
  
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service-xfusion
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  type: NodePort
