# Create a deployment using gcr.io/kodekloud/centos-ssh-enabled:node image, replica count must be 2.

# Create a service to expose this app, the service type must be NodePort, 
#   targetPort must be 8080 and nodePort should be 30012.

# Make sure all the pods are in Running state after the deployment.

# You can check the application by clicking on NodeApp button on top bar.

# You can use any labels as per your choice.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-container
        image: gcr.io/kodekloud/centos-ssh-enabled:node
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30012

  type: NodePort

