apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
  labels:
    app: secret-xfusion
spec:
  containers:
  - name: secret-container-xfusion
    image: fedora:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: secret-volume
        mountPath: /opt/apps
  volumes:
    - name: secret-volume
      secret:
        secretName: media