
# The inventory file /home/thor/ansible/inventory seems to be having some issues, please fix them. 
# The playbook needs to be run on App Server 3 in Stratos DC, so inventory file needs to be updated accordingly.

# Create a playbook /home/thor/ansible/playbook.yml and add a task to create an empty file /tmp/file.txt on App Server 3.

# Note: Validation will try to run the playbook 
# using command ansible-playbook -i inventory playbook.yml 
# so please make sure the playbook works this way without passing any extra arguments.

---
- name: 
  hosts: all
  become: yes

  tasks:
    - name: Create a empty directory
      file:
        path: /tmp/file.txt
        state: touch
        mode: "644"
