# . Jump host is our Ansible controller, and we are going to run Ansible playbooks through thor user from jump host.


# b. There is an inventory file /home/thor/ansible/inventory on jump host.
#  Using that inventory file test Ansible ping from jump host to App Server 3, make sure ping works.
#  thor@jump_host ~/ansible$ cat inventory
          stapp01 ansible_host=172.16.238.10 ansible_user=tony ansible_ssh_pass=Ir0nM@n
          stapp02 ansible_host=172.16.238.11 ansible_user=steve ansible_ssh_pass=Am3ric@
          stapp03 ansible_host=172.16.238.12 ansible_user=banner ansible_ssh_pass=BigGr33n

# 
# change the inventory file and add username into in for the ping the all managed hosts

# run the 
#     ansible -i inventory -m ping
