kubectl create secret generic mysql-secrets \
  --from-literal=MYSQL_ROOT_PASSWORD=QWERt@123ASD \
  --from-literal=MYSQL_DATABASE=lamp-wp-db \
  --from-literal=MYSQL_USER=sud \
  --from-literal=MYSQL_PASSWORD=QWERt@123ASD \
  --from-literal=MYSQL_HOST=mysql-service


# mysql-secrets.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UVdFUnRAMTIzQVNE
  MYSQL_DATABASE: bGFtcC13cC1kYg==
  MYSQL_USER: c3Vk
  MYSQL_PASSWORD: UVdFUnRAMTIzQVNE
  MYSQL_HOST: bXlzcWwtc2VydmljZQ==